# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171206_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator',
            name='graduated',
        ),
    ]
