# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 07:54
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_investigator_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestarea',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToAutoSlugClassNameDir('name'), validators=[stdimage.validators.MinSizeValidator(400, 400), stdimage.validators.MaxSizeValidator(1000, 1000)]),
        ),
    ]
