# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_interestarea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='orcid_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
