# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171206_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestarea',
            options={'ordering': ['name'], 'verbose_name': 'Area de Interes', 'verbose_name_plural': 'Areas de Interes'},
        ),
    ]
