# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171206_0315'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='interest_areas',
            field=models.ManyToManyField(blank=True, to='profiles.InterestArea'),
        ),
    ]
