# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_interest_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(),
        ),
    ]
