# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20171206_0436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['title'], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='publicationkind',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Publicacion', 'verbose_name_plural': 'Tipos de Publicaciones'},
        ),
    ]
